import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable


def workout_plan_to_pdf_bytes(user_name: str, week_start: str, week_end: str, week_number: int, workout_plan: dict) -> bytes:
    buffer = io.BytesIO()

    # Wider margins for better centering
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=60, leftMargin=60,
                            topMargin=48, bottomMargin=36)
    story = []

    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1

    meta_style = ParagraphStyle('meta', parent=styles['Normal'], spaceAfter=10)
    cell_style = ParagraphStyle('cell', parent=styles['Normal'], fontSize=9, leading=11)

    # Header
    story.append(Paragraph(f"Workout Plan — Week {week_number}", title_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"Name: {user_name}", meta_style))
    story.append(Paragraph(f"Week: {week_start} — {week_end}", meta_style))
    story.append(Spacer(1, 16))

    day_order = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']

    for i, day in enumerate(day_order):
        day_info = workout_plan.get(day)
        if not day_info:
            continue

        if i > 0:
            story.append(Spacer(1, 10))
            story.append(HRFlowable(width="100%", thickness=0.7, color=colors.grey))
            story.append(Spacer(1, 10))

        day_title = day.capitalize()
        story.append(Paragraph(f"<b>{day_title} — {day_info.get('focus','')}</b>", styles['Heading3']))
        story.append(Spacer(1, 6))

        exercises = day_info.get('exercises', [])

        if exercises:
            table_data = [[
                Paragraph('<b>Exercise</b>', styles['BodyText']),
                Paragraph('<b>Sets</b>', styles['BodyText']),
                Paragraph('<b>Reps/Duration</b>', styles['BodyText']),
                Paragraph('<b>Rest (s)</b>', styles['BodyText'])
            ]]

            notes_list = []

            for ex in exercises:
                table_data.append([
                    Paragraph(str(ex.get('name', '')), cell_style),
                    Paragraph(str(ex.get('sets', '')), cell_style),
                    Paragraph(str(ex.get('reps', '')), cell_style),
                    Paragraph(str(ex.get('rest', '')), cell_style),
                ])

                note = ex.get('notes')
                if note:
                    notes_list.append(f"• {note}")

            tbl = Table(table_data, hAlign='LEFT',
                        colWidths=[200, 55, 110, 55], repeatRows=1,spaceAfter=3,spaceBefore=6)

            tbl.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e8e8e8')),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ALIGN', (1, 1), (-1, -1), 'CENTER'),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
                ('TOPPADDING', (0, 0), (-1, -1), 3),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ]))

            story.append(tbl)
            story.append(Spacer(1, 6))

            if notes_list:
                story.append(Paragraph("<b>Notes / Instructions:</b>", styles['Italic']))
                notes_para = Paragraph("<br/>".join(notes_list),
                                       ParagraphStyle('notes', parent=styles['Normal'], fontSize=9, leading=12))
                story.append(notes_para)
                story.append(Spacer(1, 12))
        else:
            story.append(Paragraph("Rest / Active recovery", styles['Normal']))
            story.append(Spacer(1, 12))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Health Plus — follow form & safety guidance.", styles['Italic']))

    doc.build(story)

    buffer.seek(0)
    return buffer.read()
